name = "dropbox-index"
type = "webpack"
account_id = "your-account-id"
workers_dev = true
route = ""
zone_id = ""
usage_model = ""
compatibility_date = "2023-06-01"

[build]
command = "npm run build"
output_dir = "out"

[site]
bucket = "./out"
entry-point = "workers-site"

[env.production]
name = "dropbox-index-prod"